[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# Healthcheck disabled temporarily
# healthcheckPath = "/health"
# healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
